version: "3"

services:
  front:
    platform: linux/amd64
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./frontend/:/app
      - /app/node_modules

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - 9000:9000
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend
